name: HuskItemEconomy
version: ${project.version}
main: net.william278.huskitemeconomy.HuskItemEconomy
api-version: 1.16
authors: [William278]
depend: [Vault]
description: ${project.description}
commands:
  balance:
    usage: /bal
    description: View a count-up of your item balance
    aliases:
      - bal
      - money